import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { PrismaClient } from '@prisma/client'
import Header from './components/Header'
import Navigation from './components/Navigation'
import Search from './components/Search'
import RecentSearches from './components/RecentSearches'
import Title from './components/Title'
import Summary from './components/Summary'
import Review from './components/Review'
import OneWordReview from './components/OneWordReview'
import SimilarContent from './components/SimilarContent'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ results }) {
  return (
    <>
      <Head>
        <title>NextJs Primsa Skeleton</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Navigation />
        <Search />
        <OneWordReview />
        <RecentSearches />
        <Title />
        <Summary />
        <Review />
        <SimilarContent />
      </main>
    </>
  )
}

// export async function getStaticProps() {
//   const prisma = new PrismaClient();
//   const results = await prisma.result.findMany();

//   console.log(results);

//   return {
//     props: { results }
//   }
// }